<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Linkame</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,300" rel="stylesheet">
        <style>
            body {
                margin: 20px 0;
                padding: 0;
                width: 100%;
                font-family: 'Roboto', sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #1976D2;
                letter-spacing: -3px;
                font-size: 5em;
                font-weight: 100;
                margin-bottom: 0;
            }

            h1>a {
                text-decoration: none;
                color: #1976D2;
            }
            h1>a:visited, h1>a:hover{
                color: #1976D2;
            }

            h2 {
                color: #5a5a5a;
                letter-spacing: -3px;
                font-size: 2em;
                font-weight: 300;
                margin-bottom: 0;
            }

            a.link {
                text-decoration: none;
                color: #1976D2;
                font-weight: 300;
            }
            a.link:visited { 
                color: #1976D2;
            }
            a.link:hover { 
                color: #d219b1;
            }
            a.link>div {
                padding: 0 5px;
            }
            a.link>div:hover {
                background-color: #eaeaea;
            }
            
            /* Append ellipsis when text overflows its containing element: */
            .ellipses {
                width: 100%;
                display: block;
                overflow: hidden;
                white-space: nowrap;
                text-overflow: ellipsis;
            }

            header { 
                position: absolute;
                right: 0;
                top: 0;
                padding: 1rem;
            }
        </style>
    </head>
    <body>    
        <?php if ($device !== '') : ?>
            <header> <?php echo "Device: $device"; ?> </header>
         <?php endif; ?>

        <h1><a href="/">Linkame</a></h1>
        <div>An easy, simple and useful link list</div>
        <br/>
        <?php if (isset($links) && count($links) > 0) { 
            foreach ($links as $clave=>$valor)
                {
                    echo '<a class="link" href="' . $valor["url"] . '">';
                    echo "<div><h2>" . htmlspecialchars($valor["name"]) . "</h2>";
                    echo '<span class="ellipses">' . htmlspecialchars($valor["url"]) . "</span>";
                    echo '</div></a>';
                }        
        ?>            
        <?php } else { ?>
            <p>No links yet :(</a>
        <?php } ?>
    </body>
</html>
